# Generated by Django 4.0.2 on 2022-04-14 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 16, 21, 42, 4, 22476, tzinfo=utc), null=True),
        ),
    ]
