# Generated by Django 4.0.2 on 2022-04-16 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_age_alter_user_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 16, 40, 52, 848890, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=30, null=True, verbose_name='возраст'),
        ),
    ]
