# Generated by Django 4.0.2 on 2022-04-23 05:14

from django.db import migrations
from users.models import UserProfile, User


def create_profiles(apps, schema_editor):
    exclude_user_adx = UserProfile.objects.only('user').values_list('user__id', flat=True)
    users = User.objects.exclude(id__in=exclude_user_adx)
    if users.exists():
        create_profiles = [UserProfile(user=user) for user in users]
        UserProfile.objects.bulk_create(create_profiles)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
